### PR TITLE
Merged Git/Github Labs

### PR DESCRIPTION
**Pull request by borninla**
* changed title and broke lab into two parts
* added main file for students to practice branching and merging on

### CODE REVIEW

**Comment by brrcrites** [comment]
I've gotten to line 158 in the revision and I've mostly just tightened up some of the language. One thing I think probably needs to be added is which parts should be done individually and which should be done with a partner.

I'll finish up with revisions to the rest of the document tomorrow, but I think the beginning was where most of the changes were made so I expect the second half will be pretty quick to review.

**Comment by brrcrites** [comment]
It seems to me that one of the secondary things we want students to learn besides how to use git is some basic terminology. Should we have them make a terms.txt file that they need to upload as part of their final submission?

**Comment by brrcrites** [comment]
@borninla refactor is done on my side. I basically stopped reading when it got to the lab 3 content so I'll probably go over that agin after the merge. I added an objectives list at the top of section 1 and added a part 1 header to separate the two parts better and then fixed the bridge between the two to make it seems a bit less like two labs crammed together. Please review and merge when you are free (also take a look at my other comments)

**Comment by borninla** [comment]
> One thing I think probably needs to be added is which parts should be done individually and which should be done with a partner.
Do you think having partners in part 2 is enough? Also, have we thought of the case where we have an odd number of students in lab? What then?

>It seems to me that one of the secondary things we want students to learn besides how to use git is some basic terminology. Should we have them make a terms.txt file that they need to upload as part of their final submission?
Do you mean in the sense of explaining what specific Git commands do (similar to how we did so in CS 183 for Linux commands)?

**Comment by borninla** [comment]
Shall I wait for another review or is it safe to merge now?

**Comment by brrcrites** [comment]
I added a partner requirement at the top of the lab and specified that it doesn't come in until part 2. If there are an uneven number of students it gets a bit more complicated and you can either have 1 person play both roles or have the third person switch off for part of the lab.

I don't think they need to know git commands, more like have them make a text document that lists terms and their definitions like "upstream: the remote repository that your local git repository is connected to where code is sent on a push". We don't need to put it in now just something to think about.

Merging now.

**Pull request merged**
